import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, Gift, Save, Sparkles, Tag, Trash2 } from "lucide-react";
import { useState, type FormEvent } from "react";
import { merchandisingService } from "../../services/merchandisingService";
import type { CampaignType, MerchandisingCampaign, MerchandisingProductAdmin, MerchandisingStatus } from "../../types";
import styles from "./AdminMerchandisingPage.module.scss";

type CampaignDraft = { slug: string; type: CampaignType; title: string; eyebrow: string; description: string; imageUrl: string; status: MerchandisingStatus; isFeatured: boolean; startsAt: string; endsAt: string; productIds: string[] };
type PromotionDraft = { code: string; description: string; discountType: "PERCENT" | "FIXED"; amount: number; minSubtotal: number; usageLimit: string; isActive: boolean };
const blankCampaign: CampaignDraft = { slug: "", type: "GIFT_SET", title: "", eyebrow: "", description: "", imageUrl: "", status: "DRAFT", isFeatured: false, startsAt: "", endsAt: "", productIds: [] };
const blankPromotion: PromotionDraft = { code: "", description: "", discountType: "PERCENT", amount: 10, minSubtotal: 0, usageLimit: "", isActive: true };

function ProductSettings({ product, refresh }: { product: MerchandisingProductAdmin; refresh: () => Promise<void> }) {
  const [values, setValues] = useState(product); const [saved, setSaved] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); await merchandisingService.updateProduct(product.id, { lowStockThreshold: values.lowStockThreshold, sampleAvailable: values.sampleAvailable, samplePrice: values.samplePrice, backInStockEnabled: values.backInStockEnabled }); setSaved(true); await refresh(); };
  return <form className={styles.productRow} onSubmit={submit}><strong>{product.name}</strong><label>Low stock<input min="0" type="number" value={values.lowStockThreshold} onChange={(e) => setValues({ ...values, lowStockThreshold: Number(e.target.value) })} /></label><label>Sample price<input min="0" step="0.01" type="number" value={values.samplePrice ?? ""} onChange={(e) => setValues({ ...values, samplePrice: e.target.value ? Number(e.target.value) : null })} /></label><label className={styles.check}><input checked={values.sampleAvailable} type="checkbox" onChange={(e) => setValues({ ...values, sampleAvailable: e.target.checked })} />Samples</label><label className={styles.check}><input checked={values.backInStockEnabled} type="checkbox" onChange={(e) => setValues({ ...values, backInStockEnabled: e.target.checked })} />Alerts</label><button type="submit"><Save aria-hidden="true" />{saved ? "Saved" : "Save"}</button></form>;
}

export function AdminMerchandisingPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["admin", "merchandising"], queryFn: merchandisingService.getAdmin }); const data = query.data;
  const [campaign, setCampaign] = useState(blankCampaign); const [campaignId, setCampaignId] = useState<string | null>(null); const [promotion, setPromotion] = useState(blankPromotion); const [feedback, setFeedback] = useState("");
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["admin", "merchandising"] }); };
  const editCampaign = (item: MerchandisingCampaign) => { setCampaignId(item.id); setCampaign({ slug: item.slug, type: item.type, title: item.title, eyebrow: item.eyebrow ?? "", description: item.description, imageUrl: item.imageUrl ?? "", status: item.status, isFeatured: item.isFeatured, startsAt: item.startsAt?.slice(0, 16) ?? "", endsAt: item.endsAt?.slice(0, 16) ?? "", productIds: item.productIds }); };
  const saveCampaign = async (event: FormEvent) => { event.preventDefault(); const input = { ...campaign, eyebrow: campaign.eyebrow || null, imageUrl: campaign.imageUrl || null, startsAt: campaign.startsAt ? new Date(campaign.startsAt).toISOString() : null, endsAt: campaign.endsAt ? new Date(campaign.endsAt).toISOString() : null }; if (campaignId) await merchandisingService.updateCampaign(campaignId, input); else await merchandisingService.createCampaign(input); setFeedback("Campaign saved."); setCampaign(blankCampaign); setCampaignId(null); await refresh(); };
  const savePromotion = async (event: FormEvent) => { event.preventDefault(); await merchandisingService.createPromotion({ ...promotion, code: promotion.code.toUpperCase(), usageLimit: promotion.usageLimit ? Number(promotion.usageLimit) : null }); setPromotion(blankPromotion); setFeedback("Promotion published."); await refresh(); };
  return <section className={styles.page}><header><div><p>Commercial storytelling</p><h2>Merchandising studio</h2><span>Publish gift edits and recommendations, control promotion codes, samples, scarcity and customer alert queues without a code release.</span></div></header>{feedback ? <p className={styles.feedback} role="status">{feedback}</p> : null}
    <section className={styles.block}><header><Gift aria-hidden="true" /><div><p>Gift sets and recommendations</p><h3>Campaigns</h3></div></header><div className={styles.split}><form className={styles.form} onSubmit={saveCampaign}><div className={styles.two}><label>Title<input required value={campaign.title} onChange={(e) => setCampaign({ ...campaign, title: e.target.value })} /></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={campaign.slug} onChange={(e) => setCampaign({ ...campaign, slug: e.target.value })} /></label><label>Type<select value={campaign.type} onChange={(e) => setCampaign({ ...campaign, type: e.target.value as typeof campaign.type })}><option value="GIFT_SET">Gift set</option><option value="CURATED_EDIT">Curated recommendations</option></select></label><label>Status<select value={campaign.status} onChange={(e) => setCampaign({ ...campaign, status: e.target.value as typeof campaign.status })}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label>Eyebrow<input value={campaign.eyebrow} onChange={(e) => setCampaign({ ...campaign, eyebrow: e.target.value })} /></label><label>Image URL<input value={campaign.imageUrl} onChange={(e) => setCampaign({ ...campaign, imageUrl: e.target.value })} /></label><label>Starts<input type="datetime-local" value={campaign.startsAt} onChange={(e) => setCampaign({ ...campaign, startsAt: e.target.value })} /></label><label>Ends<input type="datetime-local" value={campaign.endsAt} onChange={(e) => setCampaign({ ...campaign, endsAt: e.target.value })} /></label></div><label>Description<textarea required minLength={10} rows={5} value={campaign.description} onChange={(e) => setCampaign({ ...campaign, description: e.target.value })} /></label><fieldset><legend>Products and order</legend>{data?.products.map((product) => <label className={styles.check} key={product.id}><input checked={campaign.productIds.includes(product.id)} type="checkbox" onChange={(e) => setCampaign({ ...campaign, productIds: e.target.checked ? [...campaign.productIds, product.id] : campaign.productIds.filter((id) => id !== product.id) })} />{product.name}</label>)}</fieldset><label className={styles.check}><input checked={campaign.isFeatured} type="checkbox" onChange={(e) => setCampaign({ ...campaign, isFeatured: e.target.checked })} />Featured placement</label><button type="submit"><Save aria-hidden="true" />{campaignId ? "Update campaign" : "Create campaign"}</button></form><div className={styles.list}>{data?.campaigns.map((item) => <article key={item.id}><span>{item.type} · {item.status}</span><h4>{item.title}</h4><p>{item.products.length} products</p><div><button onClick={() => editCampaign(item)} type="button">Edit</button><button onClick={async () => { if (confirm("Delete this campaign?")) { await merchandisingService.deleteCampaign(item.id); await refresh(); } }} type="button"><Trash2 aria-hidden="true" />Delete</button></div></article>)}</div></div></section>
    <section className={styles.block}><header><Tag aria-hidden="true" /><div><p>Checkout incentives</p><h3>Promotion codes</h3></div></header><div className={styles.split}><form className={styles.form} onSubmit={savePromotion}><div className={styles.two}><label>Code<input required value={promotion.code} onChange={(e) => setPromotion({ ...promotion, code: e.target.value })} /></label><label>Type<select value={promotion.discountType} onChange={(e) => setPromotion({ ...promotion, discountType: e.target.value as typeof promotion.discountType })}><option value="PERCENT">Percent</option><option value="FIXED">Fixed EUR</option></select></label><label>Amount<input required min="0.01" step="0.01" type="number" value={promotion.amount} onChange={(e) => setPromotion({ ...promotion, amount: Number(e.target.value) })} /></label><label>Minimum subtotal<input min="0" step="0.01" type="number" value={promotion.minSubtotal} onChange={(e) => setPromotion({ ...promotion, minSubtotal: Number(e.target.value) })} /></label><label>Usage limit<input min="1" type="number" value={promotion.usageLimit} onChange={(e) => setPromotion({ ...promotion, usageLimit: e.target.value })} /></label></div><label>Description<textarea required rows={3} value={promotion.description} onChange={(e) => setPromotion({ ...promotion, description: e.target.value })} /></label><button type="submit"><Sparkles aria-hidden="true" />Create promotion</button></form><div className={styles.list}>{data?.promotions.map((item) => <article key={item.id}><span>{item.discountType} · used {item.usageCount}{item.usageLimit ? ` / ${item.usageLimit}` : ""}</span><h4>{item.code}</h4><p>{item.description}</p><div><button onClick={async () => { await merchandisingService.updatePromotion(item.id, { isActive: !item.isActive }); await refresh(); }} type="button">{item.isActive ? "Pause" : "Activate"}</button><button onClick={async () => { if (confirm("Delete this promotion?")) { await merchandisingService.deletePromotion(item.id); await refresh(); } }} type="button"><Trash2 aria-hidden="true" />Delete</button></div></article>)}</div></div></section>
    <section className={styles.block}><header><Sparkles aria-hidden="true" /><div><p>Product-level controls</p><h3>Samples and stock messaging</h3></div></header><div className={styles.productList}>{data?.products.map((product) => <ProductSettings key={product.id} product={product} refresh={refresh} />)}</div></section>
    <section className={styles.block}><header><Bell aria-hidden="true" /><div><p>Customer intent</p><h3>Back-in-stock queue</h3></div></header><div className={styles.list}>{data?.alerts.map((alert) => <article key={alert.id}><span>{alert.status} · {new Date(alert.createdAt).toLocaleDateString()}</span><h4>{alert.product.name}</h4><p>{alert.email}</p>{alert.status === "PENDING" ? <div><button onClick={async () => { await merchandisingService.updateAlert(alert.id, "NOTIFIED"); await refresh(); }} type="button">Mark notified</button><button onClick={async () => { await merchandisingService.updateAlert(alert.id, "CANCELLED"); await refresh(); }} type="button">Cancel</button></div> : null}</article>)}</div></section>
  </section>;
}
