export type HomepageTheme = {
	id: string;
	collectionSlug: string;
	title: string;
	eyebrow: string;
	heroTone: "light" | "dark";
	headerTextColor: string;
	description: string;
	image: string;
	imageAlt: string;
	mobileImage?: string;
	accent: string;
	accentDark: string;
	accentSoft: string;
	borderColor: string;
	glassBackground: string;
	glassBorder: string;
	heroBackground: string;
	storyImage: string;
	storyImageAlt: string;
	surface: string;
	surfaceAlt: string;
	sectionSurface: string;
	textColor: string;
	textMutedColor: string;
	textSoftColor: string;
	buttonTextColor: string;
};
