import { useQuery } from "@tanstack/react-query";
import { Gift, Plus } from "lucide-react";
import { FallbackImage } from "../../components/common/FallbackImage/FallbackImage";
import { ProductGrid } from "../../components/commerce/ProductGrid/ProductGrid";
import { useCart } from "../../features/cart/hooks/useCart";
import { useLocalWishlist } from "../../features/products/hooks/useLocalWishlist";
import { useDocumentMetadata } from "../../hooks/useDocumentMetadata";
import { merchandisingService } from "../../services/merchandisingService";
import styles from "./GiftSetsPage.module.scss";
export function GiftSetsPage() { const query = useQuery({ queryKey: ["merchandising-campaigns"], queryFn: merchandisingService.getCampaigns }); const cart = useCart(); const { wishlist, toggleWishlist } = useLocalWishlist(); const sets = (query.data ?? []).filter((campaign) => campaign.type === "GIFT_SET"); useDocumentMetadata({ title: "Gift Sets | AVELIS", description: "Curated fragrance sets published by the AVELIS atelier.", canonicalPath: "/gift-sets" }); const addSet = (products: typeof sets[number]["products"]) => { for (const product of products) { const variant = product.variants.find((item) => item.format === "BOTTLE" && item.stock > 0) ?? product.variants.find((item) => item.stock > 0); if (variant) cart.addItem({ product, variant, quantity: 1 }); } }; return <main className={styles.page}><header><Gift aria-hidden="true" /><p>Objects of consideration</p><h1>Gift edits, composed in the atelier.</h1><span>Each edit is published independently and can change with the season—without a storefront release.</span></header><div className={styles.sets}>{query.isLoading ? <p>Preparing the gift edit…</p> : sets.map((campaign) => <section key={campaign.id}><header><FallbackImage alt={`${campaign.title} gift set`} loading="lazy" src={campaign.imageUrl} /><div><p>{campaign.eyebrow ?? "Curated gift set"}</p><h2>{campaign.title}</h2><span>{campaign.description}</span><button onClick={() => addSet(campaign.products)} type="button"><Plus aria-hidden="true" />Add available set to bag</button></div></header><ProductGrid itemListId={`gift_set_${campaign.slug}`} itemListName={campaign.title} items={campaign.products.map((product) => ({ product }))} onWishlistToggle={toggleWishlist} wishlist={wishlist} /></section>)}</div></main>; }
