export type HomepageTheme = {
	id: string;
	collectionSlug: string;
	title: string;
	eyebrow: string;
	description: string;
	image: string;
	imageAlt: string;
	mobileImage?: string;
	accent: string;
	accentDark: string;
	accentSoft: string;
	borderColor: string;
	glassBackground: string;
	glassBorder: string;
	heroBackground: string;
	storyImage: string;
	storyImageAlt: string;
	surface: string;
	surfaceAlt: string;
	textColor: string;
	buttonTextColor: string;
};
